version: "1"
checks:
  method-lines:
    config:
      threshold: 60
  file-lines:
    config:
      threshold: 350
  method-complexity:
    config:
      threshold: 10
  argument-count:
    config:
      threshold: 8

engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 50

exclude_patterns:
- "lib/"
- "models/"
- "script/"
 